-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Document"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    filename text COLLATE pg_catalog."default" NOT NULL,
    file_path text COLLATE pg_catalog."default" NOT NULL,
    uploaded_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Document_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."EvaluationJob"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    job_title text COLLATE pg_catalog."default" NOT NULL,
    cv_id text COLLATE pg_catalog."default" NOT NULL,
    project_report_id text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'queued'::text,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone NOT NULL,
    CONSTRAINT "EvaluationJob_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."EvaluationLog"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    job_id text COLLATE pg_catalog."default" NOT NULL,
    stage text COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    retry_count integer,
    "timestamp" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "EvaluationLog_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."EvaluationResult"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    job_id text COLLATE pg_catalog."default" NOT NULL,
    cv_match_rate double precision NOT NULL,
    cv_feedback text COLLATE pg_catalog."default",
    project_score double precision NOT NULL,
    project_feedback text COLLATE pg_catalog."default",
    overall_summary text COLLATE pg_catalog."default",
    completed_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    final_score double precision,
    CONSTRAINT "EvaluationResult_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public._prisma_migrations
(
    id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    checksum character varying(64) COLLATE pg_catalog."default" NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logs text COLLATE pg_catalog."default",
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    applied_steps_count integer NOT NULL DEFAULT 0,
    CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.newtable1
(
    id text COLLATE pg_catalog."default" NOT NULL,
    job_id text COLLATE pg_catalog."default" NOT NULL,
    cv_match_rate double precision NOT NULL,
    cv_feedback text COLLATE pg_catalog."default",
    project_score double precision NOT NULL,
    project_feedback text COLLATE pg_catalog."default",
    overall_summary text COLLATE pg_catalog."default",
    completed_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    final_score double precision,
    CONSTRAINT "EvaluationResult_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."EvaluationJob"
    ADD CONSTRAINT "EvaluationJob_cv_id_fkey" FOREIGN KEY (cv_id)
    REFERENCES public."Document" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."EvaluationJob"
    ADD CONSTRAINT "EvaluationJob_project_report_id_fkey" FOREIGN KEY (project_report_id)
    REFERENCES public."Document" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."EvaluationLog"
    ADD CONSTRAINT "EvaluationLog_job_id_fkey" FOREIGN KEY (job_id)
    REFERENCES public."EvaluationJob" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."EvaluationResult"
    ADD CONSTRAINT "EvaluationResult_job_id_fkey" FOREIGN KEY (job_id)
    REFERENCES public."EvaluationJob" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "EvaluationResult_job_id_key"
    ON public."EvaluationResult"(job_id);

END;